# Generated by Django 4.0.6 on 2022-07-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_options_store_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('active', 'Active'), ('deactivated', 'Deactivated')], default='in_review', max_length=15),
        ),
    ]
